       IDENTIFICATION DIVISION.
       PROGRAM-ID. P1.
       AUTHOR. WILLIAM-KEISLOHN.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SPECIAL-NAMES.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       01 STARTING_AMOUNT PIC 9 VALUE 0.
       01 ENDING_AMOUNT PIC 9 VALUE 0.
       01 DIFFERENCE_AMOUNT PIC 9 VALUE 0.
       01 MONTHS_BETWEEN PIC 9(2) VALUE 1. 
       01 PERCENT_CHANGE PIC 9P VALUE 0.
       01 PERCENT_CHANGE_YEAR PIC 9P VALUE 0.
       01 GOAL_AMOUNT PIC 9 VALUE 1000000.
       01 BIRTH_DATE.
         05 BIRTH_MONTH PIC 9(2) VALUE ZEROS.
         05 BIRTH_DAY PIC 9(2) VALUE ZEROES.
         05 BIRTH_YEAR PIC 9(4) VALUE ZEROS.
         05 BIRTH_DAY_CORRECT PIC 9 VALUE 0.
           88 DAY-TRUE VALUE 1.
           88 DAY-FALSE VALUE 0.
         05 BIRTH_DAY_COMMON PIC X.
       01 AGE PIC 9(3) VALUE 0.
       01 WS-CURRENT-DATE-FIELDS. *> FROM IBM.
         05 WS-CURRENT-DATE.
           10 WS-CURRENT-YEAR PIC 9(4).
           10 WS-CURRENT-MONTH PIC 9(2).
           10 WS-CURRENT-DAY PIC 9(2).
         05 WS-CURRENT-TIME.
           10 WS-CURRENT-HOUR PIC 9(2).
           10 WS-CURRENT-MINUTE PIC 9(2).
           10 WS-CURRENT-SECOND PIC 9(2).
           10 WS-CURRENT-MS PIC 9(2).
         05 WS-DIFF-FROM-GMT PIC S9(4).
       01 YEARS_TO_GROW PIC 9 VALUE 0.
       01 GOAL_AGE PIC 9(1) VALUE 0.

       PROCEDURE DIVISION.

           MOVE FUNCTION CURRENT-DATE TO WS-CURRENT-DATE-FIELDS
           .

       AGE-PARA.
           PERFORM BIRTH-DATE-PARA UNTIL BIRTH_DAY_CORRECT = 1
           .

       BIRTH-DATE-PARA.
           DISPLAY "PLEASE ENTER YOUR BIRTHDAY BELOW"
           .
           DISPLAY "PLEASE ENTER YOUR BIRTH YEAR: " WITH NO ADVANCING
           ACCEPT BIRTH_YEAR
           .
           DISPLAY "PLEASE ENTER YOUR BIRTH MONTH: " WITH NO ADVANCING
           ACCEPT BIRTH_MONTH
           .
           DISPLAY "PLEASE ENTER THE DAY OF THE MONTH YOU WERE BORN: "
             WITH NO ADVANCING
           ACCEPT BIRTH_DAY
           .
           DISPLAY BIRTH_DATE
           .

       COMMON-DATE-PARA.
                    


           STOP RUN. 
